### ISSUE TITLE
[Code Review] 

### ISSUE THREAD

**Issue by SeulGeek** [SeulGeek/FoodForYou#43]
- [x] There's no loading dialig when data is queried : #52 

- [x] variable names not according to android standard : #49 

- [x]  use retrofit so you don't have to worry about thread management as it becomes hard to maintain
-> scope out due to legacy code (API) : #47 

- [x] minified enabled in grade should be true not false(security problem) : #48 

- [x] add buildToolsVersion 30.0.2 : #50

- [x] instead of many nested if else statement use switch : #46 

- [x] when calling getIntent always check for not null : #51 

Other than that, good job on first app 👍 from.E
